# --- !Ups

create table "primeFactors" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "number" int not null,
  "equation" varchar not null
)

# --- !Downs

drop table "primeFactors" if exists;
